# Generated by Django 3.2.8 on 2021-10-23 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passwordmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ('name',)},
        ),
    ]
