# Generated by Django 3.2.8 on 2021-10-23 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwordmanager', '0002_alter_account_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(blank=True, max_length=100),
        ),
    ]
