# Generated by Django 3.2.8 on 2021-10-23 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passwordmanager', '0004_account_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='author',
            new_name='user',
        ),
    ]
