# Generated by Django 3.2.8 on 2021-10-26 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwordmanager', '0016_alter_account_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='logo',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
