# Generated by Django 3.2.8 on 2021-10-26 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwordmanager', '0017_auto_20211026_0437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
