# Generated by Django 3.2.8 on 2021-11-20 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwordmanager', '0018_alter_account_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='link',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
