# Generated by Django 3.2.8 on 2021-11-20 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passwordmanager', '0019_alter_account_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='logo',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
