# Generated by Django 3.2.8 on 2021-11-20 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('passwordmanager', '0020_alter_account_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='logo',
        ),
    ]
